Updated target framework to .NET8 and adjustments for .NET8
audaciaconsulting/Audacia.Core pull request #7
Opened 2024-10-24 10:04 UTC by hasham-babar-audacia

| Action | Done? |
| --- | --- |
| CHANGELOG updated | ✔ |
| Code compiles and unit tests all pass locally | ✔|
| Debug/console log code removed | ✔ |
| Commented out code removed | ✔ |
| Unit tests added/updated | ✔|
| README updated | N/A |
| Considered: <br /> - Performance <br /> - Security <br /> - Logging | N/A |
| Licenses of any new/upgraded dependencies checked, with no copyleft dependencies introduced | N/A |

2024-10-24 12:50 UTC, richardb355 requested changes

2024-10-24 12:50 UTC, richardb355 commented on src/Audacia.Core/Paging/PagingRequest.cs
> +    public record PagingRequest(int PageSize = int.MaxValue, int PageNumber = 0);
This is actually a breaking change, as records without an explicit setter are immutable. I think I'd rather keep the getter and setter as there may be consumers of the package using the setter.

2024-10-25 06:32 UTC, hasham-babar-audacia commented on src/Audacia.Core/Paging/PagingRequest.cs
> +    public record PagingRequest(int PageSize = int.MaxValue, int PageNumber = 0);
Added the getter and setter back in for both `PagingRequest` and `SortablePagingRequest`

2024-10-25 10:39 UTC, richardb355 commented on src/Audacia.Core/Paging/PagingRequest.cs
> +        public int PageSize { get; set; } = int.MaxValue;
This will need to be a nullable int like before.

2024-10-25 10:51 UTC, richardb355 approved these changes

2024-10-25 10:56 UTC, merged